---
- name: Install OpenJDK 8.
  hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install base packages
      apt: name={{ item }} state=installed
      with_items:
        - openjdk-8-jdk
    